name: murny_final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2
  chat_bubbles: ^1.5.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  flutter_typeahead: ^5.0.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^1.0.4
  bloc_concurrency: ^0.2.2
  responsive_sizer: ^3.2.0
  flutter_dash: ^1.0.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env