name: murny_final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2
  chat_bubbles: ^1.5.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  flutter_typeahead: ^5.0.1
#  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_maps_webservices: ^1.1.1
  flutter_polyline_points: ^2.0.0
  image_picker: ^1.0.4
  bloc_concurrency: ^0.2.2
  responsive_sizer: ^3.2.0
  flutter_svg: ^2.0.9
  the_widget_marker: ^1.0.0
  material_segmented_control: ^5.0.0 
  sms_autofill: ^2.3.0
  flutter_dash: ^1.0.0
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  sliding_up_panel: ^2.0.0+1
  intl: any
  avatar_glow: ^3.0.1
  google_api_headers: ^1.3.0
  awesome_snackbar_content: ^0.1.0

  file_picker: ^6.1.1

  url_launcher: ^6.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - .env
    - assets/images/carMurny.png
    - assets/images/carMurny.svg
    - assets/images/satellite.svg
    - assets/images/imageDrawer.svg
    - assets/images/imageSearch.svg
    - assets/images/imageVoice.svg
    - assets/images/imageCall.svg
    - assets/images/imageContactusWhatsapp.svg
    - assets/images/
    - assets/images/appel_pay_icon.png

